#!/usr/bin/env python3
"""Generate icon files from treemake-logo.svg for build embedding."""

import os
import struct
import sys

def main():
    script_dir = os.path.dirname(os.path.abspath(__file__))
    root_dir = os.path.dirname(script_dir)
    res_dir = os.path.join(root_dir, "resources")
    src_dir = os.path.join(root_dir, "src")
    svg_path = os.path.join(res_dir, "treemake-logo.svg")

    try:
        import cairosvg
        from PIL import Image
        import io
    except ImportError:
        print("ERROR: pip install pillow cairosvg", file=sys.stderr)
        sys.exit(1)

    sizes = [16, 32, 48, 256]
    images = {}

    for s in sizes:
        png_data = cairosvg.svg2png(url=svg_path, output_width=s, output_height=s)
        img = Image.open(io.BytesIO(png_data)).convert("RGBA")
        images[s] = img
        img.save(os.path.join(res_dir, f"icon_{s}.png"))
        print(f"  Generated icon_{s}.png")

    # Generate .ico (Windows)
    ico_path = os.path.join(res_dir, "icon.ico")
    # Pillow can save .ico directly
    images[256].save(ico_path, format="ICO",
                     sizes=[(s, s) for s in sizes],
                     append_images=[images[s] for s in sizes if s != 256])
    print(f"  Generated icon.ico")

    # Generate C header with embedded RGBA data for glfwSetWindowIcon
    # Use 48x48 for the window icon
    icon_img = images[48]
    rgba_data = icon_img.tobytes()
    w, h = icon_img.size

    header_path = os.path.join(src_dir, "icon_data.h")
    with open(header_path, "w") as f:
        f.write("// Auto-generated by scripts/generate_icons.py\n")
        f.write("#pragma once\n\n")
        f.write(f"static const int ICON_WIDTH  = {w};\n")
        f.write(f"static const int ICON_HEIGHT = {h};\n")
        f.write(f"static const unsigned char ICON_RGBA[{len(rgba_data)}] = {{\n")
        for i in range(0, len(rgba_data), 16):
            chunk = rgba_data[i:i+16]
            f.write("    " + ", ".join(f"0x{b:02x}" for b in chunk) + ",\n")
        f.write("};\n")
    print(f"  Generated icon_data.h ({len(rgba_data)} bytes)")

    print("Done.")

if __name__ == "__main__":
    main()
